In [144]:
%load_ext autoreload
%autoreload 2
from labels import Image, Label, Roi, Mask
from patches import Patch
import cv2
import numpy as np
import matplotlib.pyplot as plt
import glob

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [147]:
images = sorted(glob.glob("/home/pi/Programs/python-programs/roi2patches/test_source_images/*.tif"))
images

['/home/pi/Programs/python-programs/roi2patches/test_source_images/11692a_x40_06.tif',
 '/home/pi/Programs/python-programs/roi2patches/test_source_images/11696_x40_10.tif',
 '/home/pi/Programs/python-programs/roi2patches/test_source_images/11704_x40_02.tif',
 '/home/pi/Programs/python-programs/roi2patches/test_source_images/11712_x40_08.tif',
 '/home/pi/Programs/python-programs/roi2patches/test_source_images/11715_x40_08.tif',
 '/home/pi/Programs/python-programs/roi2patches/test_source_images/11720b_x40_02.tif',
 '/home/pi/Programs/python-programs/roi2patches/test_source_images/11725a_x40_02.tif',
 '/home/pi/Programs/python-programs/roi2patches/test_source_images/11736_x40_04.tif',
 '/home/pi/Programs/python-programs/roi2patches/test_source_images/11743_x40_09.tif',
 '/home/pi/Programs/python-programs/roi2patches/test_source_images/11749_x40_10.tif']

In [148]:
for image in images:
    im = Image(image)
    im.create_roi()
    label = Label(im)
    label.get_data()
    label.save_label_image()
    mask = Mask(im)
    mask.load_rel_label(label)
    mask.get_data()
    for (x,y), value in np.ndenumerate(mask.data[size[0]:shape[0]-size[0], size[1]:shape[1]-size[1]]):
        x += 28
        y += 28
        flag = value
        if flag != 0:
            p = Patch(mask, [28, 28], [x, y], '/home/pi/Programs/python-programs/roi2patches/test_data', '.png')
            p.set_type(flag)
            p.create_data()
            p.save()

/home/pi/Programs/python-programs/roi2patches/test_source_images/11692a_x40_06_label.tif
[[[190 171 196]
  [187 167 194]
  [191 174 194]
  ..., 
  [214 216 215]
  [215 216 216]
  [215 217 217]]

 [[188 171 195]
  [186 168 193]
  [190 173 195]
  ..., 
  [214 215 215]
  [214 215 215]
  [214 216 216]]

 [[189 173 196]
  [186 171 194]
  [192 174 197]
  ..., 
  [214 215 215]
  [214 215 215]
  [214 216 216]]

 ..., 
 [[215 217 217]
  [215 217 217]
  [215 217 217]
  ..., 
  [212 211 212]
  [208 205 208]
  [205 199 205]]

 [[215 217 217]
  [215 217 217]
  [216 217 217]
  ..., 
  [217 216 217]
  [216 214 215]
  [214 211 213]]

 [[215 217 217]
  [215 217 217]
  [216 218 217]
  ..., 
  [215 214 216]
  [217 216 217]
  [216 215 216]]]
/home/pi/Programs/python-programs/roi2patches/test_source_images/11692a_x40_06_mask.npy


/home/pi/Programs/python-programs/roi2patches/patches.py:46: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  self.xy[1]-self.size[1]/2:self.xy[1]+self.size[1]/2]


/home/pi/Programs/python-programs/roi2patches/test_source_images/11696_x40_10_label.tif
[[[114  74 183]
  [104  68 178]
  [ 98  66 177]
  ..., 
  [213 212 216]
  [213 212 216]
  [213 212 216]]

 [[103  27 170]
  [114  52 182]
  [107  60 178]
  ..., 
  [213 212 215]
  [213 212 215]
  [213 212 215]]

 [[104  29 168]
  [112  46 180]
  [108  54 181]
  ..., 
  [213 211 215]
  [212 211 215]
  [212 211 215]]

 ..., 
 [[213 213 218]
  [214 213 219]
  [214 214 219]
  ..., 
  [217 219 219]
  [217 219 219]
  [217 219 218]]

 [[213 212 219]
  [213 213 219]
  [214 213 219]
  ..., 
  [217 219 218]
  [217 218 218]
  [217 218 218]]

 [[213 212 219]
  [213 212 219]
  [213 212 219]
  ..., 
  [217 218 218]
  [216 218 218]
  [216 218 218]]]
/home/pi/Programs/python-programs/roi2patches/test_source_images/11696_x40_10_mask.npy
/home/pi/Programs/python-programs/roi2patches/test_source_images/11704_x40_02_label.tif
[[[217 218 218]
  [217 218 218]
  [217 218 218]
  ..., 
  [217 219 219]
  [217 219 219]
  [217